spring.application.name=tumaholenkhatho

# H2 database settings
spring.datasource.url=jdbc:h2:mem:enviro365
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Enables the H2 web console at /h2-console for inspecting data visually
spring.h2.console.enabled=true

# Waits for Hibernate to create tables before data.sql tries to insert into them
spring.jpa.defer-datasource-initialization=true